fix(logger): import pino directly instead of using dynamic
> ReferenceError: require is not defined in ES module scope, you can use import instead upon seeding